##
##  Makefile -- Build procedure for sample qkem Apache module
##  Autogenerated via ``apxs -n qkem -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
MOD_INCLUDES=-Ilib/liboqs/build/include
MOD_LDFLAGS=-lssl -Llib/liboqs/build/lib/ -l:liboqs.a
include /usr/share/apache2/build/special.mk

#   the used tools
APACHECTL=apachectl

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_qkem.o mod_qkem.lo mod_qkem.slo mod_qkem.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/qkem

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

